spring:
  application:
    name: 2026.elasticsearch

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

elk:
  host: localhost
  username: elastic
  password: indddid2026
  security-enabled: false
